[project]
name = "adventure-works"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tranduc2204", email = "trandc3015@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "airflow-dbt~=0.4.0",
    "dbt-autofix~=0.18.0",
    "dbt-core~=1.11.0",
    "dbt-snowflake~=1.11.0",
    "dlt[snowflake]==1.30.0",
    "pandas>=2.0.0",
    "pymssql>=2.3.0",
    "python-dotenv>=1.0.0",
    "sqlalchemy>=2.0.0",
]

[project.scripts]
adventure-works = "adventure_works:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
