-- 1. Switch to appropriate admin role
USE ROLE ACCOUNTADMIN;

-- 2. Variables (modify these to match your environment)
SET ROLE_NAME = 'INGEST_ROLE';
SET USER_NAME = 'INGEST_USER';
SET WAREHOUSE_NAME = 'COMPUTE_WH';      -- Your loading warehouse
SET DB_NAME = 'ADVENTUREWORKS';               -- Your target database

-- 3. Create the Database & Warehouse (if not already existing)
CREATE DATABASE IF NOT EXISTS IDENTIFIER($DB_NAME);
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($WAREHOUSE_NAME)
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- 4. Create the dedicated Ingestion Role
CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_NAME);

-- 5. Grant Warehouse usage to the Ingestion Role
GRANT USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE_NAME) TO ROLE IDENTIFIER($ROLE_NAME);

-- 6. Grant Database permissions
-- (dlt creates schemas, tables, and internal stages to stage and copy files)
GRANT USAGE ON DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT CREATE SCHEMA ON DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);

-- Grant privileges for any existing and future schemas/tables/stages in the database
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);

GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);

GRANT ALL PRIVILEGES ON ALL STAGES IN DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT ALL PRIVILEGES ON FUTURE STAGES IN DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);

-- 7. Create the Service Account User with Key Pair
-- Paste the content of rsa_key.pub (excluding header, footer, and newlines)
CREATE USER IF NOT EXISTS IDENTIFIER($USER_NAME)
    RSA_PUBLIC_KEY = '<PASTE_RSA_PUBLIC_KEY_STRING_HERE>'
    DEFAULT_ROLE = $ROLE_NAME
    DEFAULT_WAREHOUSE = $WAREHOUSE_NAME
    DEFAULT_NAMESPACE = $DB_NAME
    MUST_CHANGE_PASSWORD = FALSE;

-- 8. Assign the Ingestion Role to the User
GRANT ROLE IDENTIFIER($ROLE_NAME) TO USER IDENTIFIER($USER_NAME);

-- (Optional) Make sure the role hierarchy connects to SYSADMIN for visibility
GRANT ROLE IDENTIFIER($ROLE_NAME) TO ROLE SYSADMIN;